// GENERATED FILE — do not edit by hand, and do not hand-maintain a
// second copy of any of this. Regenerate with:
//     node scripts/sync/generate-web-providers.mjs
//
// Source: src/core/model/sources/omniroute.json @ 443d669
// Only providers absent from ./providers.ts appear here, so curated entries stay
// authoritative. Each entry is emitted with just the five fields the `Provider`
// type requires plus what the snapshot can state truthfully.

import type { Provider } from "../../types";

/** Free-tier providers missing from the curated maps. Sorted ahead of everything
 * else so the free tier is what a user sees first. */
export const GENERATED_FREE_TIER_PROVIDERS: Record<string, Provider> = {
  "agy": { id: "agy", alias: "ag", name: "Agy", icon: "hub", color: "#DB2777", authType: "oauth" },
  "aihorde": { id: "aihorde", alias: "ai", name: "Aihorde", icon: "hub", color: "#EA580C", website: "https://oai.aihorde.net", authType: "apikey", noAuth: true },
  "ainative": { id: "ainative", alias: "ain", name: "Ainative", icon: "hub", color: "#CA8A04", website: "https://api.ainative.studio", authType: "apikey" },
  "ant-ling": { id: "ant-ling", alias: "an", name: "Ant Ling", icon: "hub", color: "#0D9488", website: "https://api.ant-ling.com", authType: "apikey" },
  "anyapi": { id: "anyapi", alias: "any", name: "Anyapi", icon: "hub", color: "#0891B2", website: "https://api.anyapi.ai", authType: "apikey" },
  "auggie": { id: "auggie", alias: "au", name: "Auggie", icon: "hub", color: "#9333EA", noAuth: true },
  "auriko": { id: "auriko", alias: "aur", name: "Auriko", icon: "hub", color: "#C026D3", website: "https://api.auriko.ai", authType: "apikey" },
  "baichuan": { id: "baichuan", alias: "ba", name: "Baichuan", icon: "hub", color: "#E11D48", website: "https://api.baichuan-ai.com", authType: "apikey" },
  "charm-hyper": { id: "charm-hyper", alias: "ch", name: "Charm Hyper", icon: "hub", color: "#7C3AED", website: "https://hyper.charm.land", authType: "apikey" },
  "chat-oripe": { id: "chat-oripe", alias: "cha", name: "Chat Oripe", icon: "hub", color: "#DB2777", website: "https://api.oriper.com", authType: "apikey" },
  "chatanywhere": { id: "chatanywhere", alias: "chat", name: "Chatanywhere", icon: "hub", color: "#DC2626", website: "https://api.chatanywhere.org", authType: "apikey" },
  "chipotle": { id: "chipotle", alias: "chi", name: "Chipotle", icon: "hub", color: "#EA580C", website: "https://amelia.chipotle.com", noAuth: true },
  "cloudcode-one": { id: "cloudcode-one", alias: "cl", name: "Cloudcode One", icon: "hub", color: "#CA8A04", website: "https://api.cloudcode.one", authType: "apikey" },
  "cloudflare-playground": { id: "cloudflare-playground", alias: "clo", name: "Cloudflare Playground", icon: "hub", color: "#0D9488", website: "https://playground.ai.cloudflare.com", noAuth: true },
  "codex-app-server": { id: "codex-app-server", alias: "co", name: "Codex App Server", icon: "hub", color: "#0891B2", noAuth: true },
  "coze": { id: "coze", alias: "coz", name: "Coze", icon: "hub", color: "#9333EA", website: "https://api.coze.com", authType: "apikey" },
  "dahl": { id: "dahl", alias: "da", name: "Dahl", icon: "hub", color: "#C026D3", website: "https://inference.dahl.global", authType: "apikey" },
  "deepinfra": { id: "deepinfra", alias: "de", name: "Deepinfra", icon: "hub", color: "#E11D48", website: "https://api.deepinfra.com", authType: "apikey" },
  "devin-cli-agentic": { id: "devin-cli-agentic", alias: "dev", name: "Devin Cli Agentic", icon: "hub", color: "#65A30D", noAuth: true },
  "dgrid": { id: "dgrid", alias: "dg", name: "Dgrid", icon: "hub", color: "#059669", website: "https://api.dgrid.ai", authType: "apikey" },
  "dify": { id: "dify", alias: "di", name: "Dify", icon: "hub", color: "#0284C7", website: "https://api.dify.ai", authType: "apikey" },
  "doubao": { id: "doubao", alias: "do", name: "Doubao", icon: "hub", color: "#6D28D9", website: "https://ark.cn-beijing.volces.com", authType: "apikey" },
  "duckduckgo-web": { id: "duckduckgo-web", alias: "du", name: "Duckduckgo Web", icon: "hub", color: "#A21CAF", website: "https://duckduckgo.com", noAuth: true },
  "dxnt": { id: "dxnt", alias: "dx", name: "Dxnt", icon: "hub", color: "#BE123C", website: "https://www.dxnt.com", authType: "apikey" },
  "electronhub": { id: "electronhub", alias: "el", name: "Electronhub", icon: "hub", color: "#2563EB", website: "https://api.electronhub.ai", authType: "apikey" },
  "fastrouter": { id: "fastrouter", alias: "fa", name: "Fastrouter", icon: "hub", color: "#7C3AED", website: "https://api.fastrouter.ai", authType: "apikey" },
  "featherless-ai": { id: "featherless-ai", alias: "fe", name: "Featherless Ai", icon: "hub", color: "#DB2777", website: "https://api.featherless.ai", authType: "apikey" },
  "felo-web": { id: "felo-web", alias: "fel", name: "Felo Web", icon: "hub", color: "#DC2626", website: "https://felo.ai", noAuth: true },
  "free-ai": { id: "free-ai", alias: "fr", name: "Free Ai", icon: "hub", color: "#CA8A04", website: "https://api.free.ai", authType: "apikey" },
  "freebuff": { id: "freebuff", alias: "fre", name: "Freebuff", icon: "hub", color: "#16A34A", website: "https://www.codebuff.com", authType: "apikey" },
  "freeinference": { id: "freeinference", alias: "free", name: "Freeinference", icon: "hub", color: "#0D9488", website: "https://freeinference.org", authType: "apikey" },
  "freemodel-dev": { id: "freemodel-dev", alias: "freem", name: "Freemodel Dev", icon: "hub", color: "#0891B2", website: "https://api.freemodel.dev", authType: "apikey" },
  "friendliai": { id: "friendliai", alias: "fri", name: "Friendliai", icon: "hub", color: "#9333EA", website: "https://api.friendli.ai", authType: "apikey" },
  "hcnsec": { id: "hcnsec", alias: "hc", name: "Hcnsec", icon: "hub", color: "#F97316", website: "https://api.hcnsec.cn", authType: "apikey" },
  "helyxai": { id: "helyxai", alias: "he", name: "Helyxai", icon: "hub", color: "#65A30D", website: "https://helyxai.space", authType: "apikey" },
  "huggingchat": { id: "huggingchat", alias: "hu", name: "Huggingchat", icon: "hub", color: "#059669", website: "https://huggingface.co", authType: "apikey" },
  "iflytek": { id: "iflytek", alias: "if", name: "Iflytek", icon: "hub", color: "#A21CAF", website: "https://spark-api-open.xf-yun.com", authType: "apikey" },
  "inception": { id: "inception", alias: "in", name: "Inception", icon: "hub", color: "#BE123C", website: "https://api.inceptionlabs.ai", authType: "apikey" },
  "inference-net": { id: "inference-net", alias: "inf", name: "Inference Net", icon: "hub", color: "#2563EB", website: "https://api.inference.net", authType: "apikey" },
  "internlm": { id: "internlm", alias: "int", name: "Internlm", icon: "hub", color: "#7C3AED", website: "https://chat.intern-ai.org.cn", authType: "apikey" },
  "liquid": { id: "liquid", alias: "li", name: "Liquid", icon: "hub", color: "#DC2626", website: "https://inference.liquid.ai", authType: "apikey" },
  "literouter": { id: "literouter", alias: "lit", name: "Literouter", icon: "hub", color: "#EA580C", website: "https://api.literouter.com", authType: "apikey" },
  "llm-kiwi": { id: "llm-kiwi", alias: "ll", name: "Llm Kiwi", icon: "hub", color: "#CA8A04", website: "https://api.llm.kiwi", authType: "apikey" },
  "llmgateway": { id: "llmgateway", alias: "llm", name: "Llmgateway", icon: "hub", color: "#0D9488", website: "https://api.llmgateway.io", authType: "apikey" },
  "lmarena": { id: "lmarena", alias: "lm", name: "Lmarena", icon: "hub", color: "#0891B2", website: "https://arena.ai", authType: "apikey" },
  "logfare": { id: "logfare", alias: "lo", name: "Logfare", icon: "hub", color: "#4F46E5", website: "https://logfare.ai", authType: "apikey" },
  "meganova-ai": { id: "meganova-ai", alias: "me", name: "Meganova Ai", icon: "hub", color: "#C026D3", website: "https://api.meganova.ai", authType: "apikey" },
  "mistral": { id: "mistral", alias: "mi", name: "Mistral", icon: "hub", color: "#E11D48", website: "https://api.mistral.ai", authType: "apikey" },
  "mixlayer": { id: "mixlayer", alias: "mix", name: "Mixlayer", icon: "hub", color: "#F97316", website: "https://models.mixlayer.ai", authType: "apikey" },
  "mnn-ai": { id: "mnn-ai", alias: "mn", name: "Mnn Ai", icon: "hub", color: "#65A30D", website: "https://api.mnnai.ru", authType: "apikey" },
  "monsterapi": { id: "monsterapi", alias: "mo", name: "Monsterapi", icon: "hub", color: "#6D28D9", website: "https://api.monsterapi.ai", authType: "apikey" },
  "muse-spark-web": { id: "muse-spark-web", alias: "mu", name: "Muse Spark Web", icon: "hub", color: "#BE123C", website: "https://www.meta.ai", authType: "apikey" },
  "naga-ac": { id: "naga-ac", alias: "na", name: "Naga Ac", icon: "hub", color: "#2563EB", website: "https://api.naga.ac" },
  "naga-ai": { id: "naga-ai", alias: "nag", name: "Naga Ai", icon: "hub", color: "#7C3AED", website: "https://api.naga.ac", authType: "apikey" },
  "nara": { id: "nara", alias: "nar", name: "Nara", icon: "hub", color: "#DB2777", website: "https://router.bynara.id", authType: "apikey" },
  "navy": { id: "navy", alias: "nav", name: "Navy", icon: "hub", color: "#DC2626", website: "https://api.navy", authType: "apikey" },
  "novita": { id: "novita", alias: "no", name: "Novita", icon: "hub", color: "#0D9488", website: "https://api.novita.ai", authType: "apikey" },
  "ofoxai": { id: "ofoxai", alias: "of", name: "Ofoxai", icon: "hub", color: "#9333EA", website: "https://api.ofox.ai", authType: "apikey" },
  "ollama-cloud": { id: "ollama-cloud", alias: "ol", name: "Ollama Cloud", icon: "hub", color: "#C026D3", website: "https://ollama.com", authType: "apikey" },
  "openadapter": { id: "openadapter", alias: "op", name: "Openadapter", icon: "hub", color: "#E11D48", website: "https://api.openadapter.in", authType: "apikey" },
  "opencode": { id: "opencode", alias: "ope", name: "Opencode", icon: "hub", color: "#F97316", website: "https://opencode.ai", authType: "apikey", noAuth: true },
  "openference": { id: "openference", alias: "open", name: "Openference", icon: "hub", color: "#65A30D", website: "https://api.openference.com", authType: "oauth" },
  "openference-api": { id: "openference-api", alias: "openf", name: "Openference Api", icon: "hub", color: "#059669", website: "https://api.openference.com", authType: "apikey" },
  "openvecta": { id: "openvecta", alias: "openv", name: "Openvecta", icon: "hub", color: "#6D28D9", website: "https://api.openvecta.com", authType: "apikey" },
  "pioneer": { id: "pioneer", alias: "pi", name: "Pioneer", icon: "hub", color: "#A21CAF", website: "https://api.pioneer.ai", authType: "apikey" },
  "poixe-ai": { id: "poixe-ai", alias: "po", name: "Poixe Ai", icon: "hub", color: "#BE123C", website: "https://api.poixe.com", authType: "apikey" },
  "pollinations": { id: "pollinations", alias: "pol", name: "Pollinations", icon: "hub", color: "#2563EB", website: "https://gen.pollinations.ai" },
  "qwen-web": { id: "qwen-web", alias: "qw", name: "Qwen Web", icon: "hub", color: "#DC2626", website: "https://chat.qwen.ai", authType: "apikey" },
  "requesty": { id: "requesty", alias: "re", name: "Requesty", icon: "hub", color: "#CA8A04", website: "https://router.requesty.ai", authType: "apikey" },
  "routeway": { id: "routeway", alias: "ro", name: "Routeway", icon: "hub", color: "#16A34A", website: "https://api.routeway.ai", authType: "apikey" },
  "sarvam": { id: "sarvam", alias: "sa", name: "Sarvam", icon: "hub", color: "#0891B2", website: "https://api.sarvam.ai", authType: "apikey" },
  "sealion": { id: "sealion", alias: "se", name: "Sealion", icon: "hub", color: "#9333EA", website: "https://api.sea-lion.ai", authType: "apikey" },
  "sensenova": { id: "sensenova", alias: "sen", name: "Sensenova", icon: "hub", color: "#C026D3", website: "https://token.sensenova.cn", authType: "apikey" },
  "sparkdesk": { id: "sparkdesk", alias: "sp", name: "Sparkdesk", icon: "hub", color: "#F97316", website: "https://spark-api-open.xf-yun.com", authType: "apikey" },
  "speka": { id: "speka", alias: "spe", name: "Speka", icon: "hub", color: "#65A30D", website: "https://speka.me", authType: "apikey" },
  "stepfun": { id: "stepfun", alias: "st", name: "Stepfun", icon: "hub", color: "#059669", website: "https://api.stepfun.com", authType: "apikey" },
  "t3-web": { id: "t3-web", alias: "t3", name: "T3 Web", icon: "hub", color: "#0284C7", website: "https://t3.chat", authType: "apikey" },
  "tencent-aistudio-web": { id: "tencent-aistudio-web", alias: "te", name: "Tencent Aistudio Web", icon: "hub", color: "#A21CAF", website: "https://aistudio.tencent.ai", authType: "apikey" },
  "theoldllm": { id: "theoldllm", alias: "th", name: "Theoldllm", icon: "hub", color: "#BE123C", website: "https://theoldllm.vercel.app", noAuth: true },
  "tinycms-web": { id: "tinycms-web", alias: "ti", name: "Tinycms Web", icon: "hub", color: "#2563EB", website: "https://gov.freegpt.win", authType: "apikey" },
  "tokenreply": { id: "tokenreply", alias: "to", name: "Tokenreply", icon: "hub", color: "#7C3AED", website: "https://api.tokenreply.com", authType: "apikey" },
  "typhoon": { id: "typhoon", alias: "ty", name: "Typhoon", icon: "hub", color: "#DC2626", website: "https://api.opentyphoon.ai", authType: "apikey" },
  "unorouter": { id: "unorouter", alias: "un", name: "Unorouter", icon: "hub", color: "#CA8A04", website: "https://api.unorouter.com", authType: "apikey" },
  "veoaifree-web": { id: "veoaifree-web", alias: "ve", name: "Veoaifree Web", icon: "hub", color: "#16A34A", website: "https://veoaifree.com", noAuth: true },
  "void-ai": { id: "void-ai", alias: "vo", name: "Void Ai", icon: "hub", color: "#0891B2", website: "https://api.voidai.app", authType: "apikey" },
  "yolo-auto": { id: "yolo-auto", alias: "yo", name: "Yolo Auto", icon: "hub", color: "#4F46E5", website: "https://yolo-auto.com", authType: "apikey" },
  "yuanbao-web": { id: "yuanbao-web", alias: "yu", name: "Yuanbao Web", icon: "hub", color: "#9333EA", website: "https://yuanbao.tencent.com", authType: "apikey" },
  "zai-web": { id: "zai-web", alias: "za", name: "Zai Web", icon: "hub", color: "#C026D3", website: "https://chat.z.ai", authType: "apikey" },
  "zcode": { id: "zcode", alias: "zc", name: "Zcode", icon: "hub", color: "#E11D48", noAuth: true },
  "zenmux": { id: "zenmux", alias: "ze", name: "Zenmux", icon: "hub", color: "#F97316", website: "https://zenmux.ai", authType: "apikey" },
  "zenmux-free": { id: "zenmux-free", alias: "zen", name: "Zenmux Free", icon: "hub", color: "#65A30D", website: "https://zenmux.ai", authType: "apikey" },
  "zerolimitai": { id: "zerolimitai", alias: "zer", name: "Zerolimitai", icon: "hub", color: "#059669", website: "https://www.zerolimitai.com", authType: "apikey" },
  "zylo-api": { id: "zylo-api", alias: "zy", name: "Zylo Api", icon: "hub", color: "#0284C7", website: "https://api.zyloai.net", authType: "apikey" },
};

/** Non-free providers, kept in a separate map so the free tier stays a single
 * import and AGENTS.md's free-tier-only scope stays easy to audit. */
export const GENERATED_OTHER_PROVIDERS: Record<string, Provider> = {
  "adapta-web": { id: "adapta-web", alias: "ad", name: "Adapta Web", icon: "hub", color: "#6D28D9", website: "https://agent.adapta.one", authType: "apikey" },
  "alibaba": { id: "alibaba", alias: "al", name: "Alibaba", icon: "hub", color: "#BE123C", website: "https://dashscope-intl.aliyuncs.com", authType: "apikey" },
  "alibaba-cn": { id: "alibaba-cn", alias: "ali", name: "Alibaba Cn", icon: "hub", color: "#2563EB", website: "https://dashscope.aliyuncs.com", authType: "apikey" },
  "bai": { id: "bai", alias: "bai", name: "Bai", icon: "hub", color: "#DC2626", website: "https://api.b.ai", authType: "apikey" },
  "bailian-coding-plan": { id: "bailian-coding-plan", alias: "bail", name: "Bailian Coding Plan", icon: "hub", color: "#EA580C", website: "https://token-plan.ap-southeast-1.maas.aliyuncs.com", authType: "apikey" },
  "bedrock": { id: "bedrock", alias: "be", name: "Bedrock", icon: "hub", color: "#CA8A04", authType: "apikey" },
  "blackbox-web": { id: "blackbox-web", alias: "bl", name: "Blackbox Web", icon: "hub", color: "#16A34A", website: "https://app.blackbox.ai", authType: "apikey" },
  "chatgpt-web": { id: "chatgpt-web", alias: "chatg", name: "Chatgpt Web", icon: "hub", color: "#0D9488", website: "https://chatgpt.com", authType: "apikey" },
  "chatgpt-web-codex": { id: "chatgpt-web-codex", alias: "chatgp", name: "Chatgpt Web Codex", icon: "hub", color: "#0891B2", website: "https://chatgpt.com", authType: "apikey" },
  "cheaperinference": { id: "cheaperinference", alias: "che", name: "Cheaperinference", icon: "hub", color: "#4F46E5", website: "https://api.cheaperinference.com", authType: "apikey" },
  "chenzk": { id: "chenzk", alias: "chen", name: "Chenzk", icon: "hub", color: "#9333EA", website: "https://chenzk.top", authType: "apikey" },
  "claude-web": { id: "claude-web", alias: "cla", name: "Claude Web", icon: "hub", color: "#F97316", website: "https://claude.ai", authType: "apikey" },
  "clinepass": { id: "clinepass", alias: "cli", name: "Clinepass", icon: "hub", color: "#059669", website: "https://api.cline.bot", authType: "oauth" },
  "clova-studio": { id: "clova-studio", alias: "clov", name: "Clova Studio", icon: "hub", color: "#0284C7", website: "https://clovastudio.stream.ntruss.com", authType: "apikey" },
  "codebuddy-cn": { id: "codebuddy-cn", alias: "cod", name: "Codebuddy Cn", icon: "hub", color: "#6D28D9", website: "https://copilot.tencent.com", authType: "oauth" },
  "codestral": { id: "codestral", alias: "code", name: "Codestral", icon: "hub", color: "#A21CAF", website: "https://codestral.mistral.ai", authType: "apikey" },
  "command-code": { id: "command-code", alias: "com", name: "Command Code", icon: "hub", color: "#2563EB", website: "https://api.commandcode.ai", authType: "apikey" },
  "conol-web": { id: "conol-web", alias: "con", name: "Conol Web", icon: "hub", color: "#7C3AED", website: "https://conol.ai", authType: "apikey" },
  "copilot-m365-web": { id: "copilot-m365-web", alias: "cop", name: "Copilot M365 Web", icon: "hub", color: "#DB2777", authType: "apikey" },
  "copilot-web": { id: "copilot-web", alias: "copi", name: "Copilot Web", icon: "hub", color: "#DC2626", authType: "apikey" },
  "crof": { id: "crof", alias: "cr", name: "Crof", icon: "hub", color: "#EA580C", website: "https://crof.ai", authType: "apikey" },
  "cursor-api": { id: "cursor-api", alias: "cu", name: "Cursor Api", icon: "hub", color: "#16A34A", website: "https://api2.cursor.sh", authType: "apikey" },
  "databricks": { id: "databricks", alias: "dat", name: "Databricks", icon: "hub", color: "#0D9488", website: "https://adb-0000000000000000.0.azuredatabricks.net", authType: "apikey" },
  "deepai": { id: "deepai", alias: "dee", name: "Deepai", icon: "hub", color: "#0891B2", website: "https://api.deepai.org", authType: "apikey" },
  "devin-cli": { id: "devin-cli", alias: "devi", name: "Devin Cli", icon: "hub", color: "#9333EA", authType: "oauth" },
  "devin-desktop": { id: "devin-desktop", alias: "devin", name: "Devin Desktop", icon: "hub", color: "#C026D3", website: "https://server.codeium.com", authType: "oauth" },
  "digitalocean": { id: "digitalocean", alias: "dig", name: "Digitalocean", icon: "hub", color: "#E11D48", website: "https://inference.do-ai.run", authType: "apikey" },
  "dit": { id: "dit", alias: "dit", name: "Dit", icon: "hub", color: "#F97316", website: "https://api.dit.ai", authType: "apikey" },
  "doubao-web": { id: "doubao-web", alias: "dou", name: "Doubao Web", icon: "hub", color: "#65A30D", website: "https://www.dola.com", authType: "apikey" },
  "factory": { id: "factory", alias: "fac", name: "Factory", icon: "hub", color: "#059669", website: "https://api.factory.ai", authType: "apikey" },
  "freeaiapikey": { id: "freeaiapikey", alias: "freea", name: "Freeaiapikey", icon: "hub", color: "#0284C7", website: "https://api.freeaiapikey.com", authType: "apikey" },
  "g4f-gemini": { id: "g4f-gemini", alias: "g4", name: "G4f Gemini", icon: "hub", color: "#6D28D9", website: "https://g4f.space" },
  "g4f-groq": { id: "g4f-groq", alias: "g4f", name: "G4f Groq", icon: "hub", color: "#A21CAF", website: "https://g4f.space" },
  "g4f-nvidia": { id: "g4f-nvidia", alias: "g4fn", name: "G4f Nvidia", icon: "hub", color: "#BE123C", website: "https://g4f.space" },
  "g4f-ollama": { id: "g4f-ollama", alias: "g4fo", name: "G4f Ollama", icon: "hub", color: "#2563EB", website: "https://g4f.space" },
  "g4f-pollinations": { id: "g4f-pollinations", alias: "g4fp", name: "G4f Pollinations", icon: "hub", color: "#7C3AED", website: "https://g4f.space" },
  "galadriel": { id: "galadriel", alias: "ga", name: "Galadriel", icon: "hub", color: "#DB2777", website: "https://api.galadriel.ai", authType: "apikey" },
  "gemini-web": { id: "gemini-web", alias: "ge", name: "Gemini Web", icon: "hub", color: "#DC2626", website: "https://gemini.google.com", authType: "apikey" },
  "ghe-copilot": { id: "ghe-copilot", alias: "gh", name: "Ghe Copilot", icon: "hub", color: "#EA580C", website: "https://api.githubcopilot.com", authType: "oauth" },
  "gigachat": { id: "gigachat", alias: "gi", name: "Gigachat", icon: "hub", color: "#CA8A04", website: "https://gigachat.devices.sberbank.ru", authType: "apikey" },
  "gitlab-duo": { id: "gitlab-duo", alias: "git", name: "Gitlab Duo", icon: "hub", color: "#0D9488", website: "https://gitlab.com", authType: "oauth" },
  "gitlawb": { id: "gitlawb", alias: "gitl", name: "Gitlawb", icon: "hub", color: "#0891B2", website: "https://opengateway.gitlawb.com", authType: "apikey" },
  "gitlawb-gmi": { id: "gitlawb-gmi", alias: "gitla", name: "Gitlawb Gmi", icon: "hub", color: "#4F46E5", website: "https://opengateway.gitlawb.com", authType: "apikey" },
  "glmt": { id: "glmt", alias: "gl", name: "Glmt", icon: "hub", color: "#E11D48", website: "https://api.z.ai", authType: "apikey" },
  "grok-cli": { id: "grok-cli", alias: "gr", name: "Grok Cli", icon: "hub", color: "#F97316", website: "https://cli-chat-proxy.grok.com", authType: "oauth" },
  "hailuo-web": { id: "hailuo-web", alias: "ha", name: "Hailuo Web", icon: "hub", color: "#059669", website: "https://chat.minimax.io", authType: "apikey" },
  "haiper": { id: "haiper", alias: "hai", name: "Haiper", icon: "hub", color: "#0284C7", website: "https://api.haiper.ai", authType: "apikey" },
  "helixmind": { id: "helixmind", alias: "hel", name: "Helixmind", icon: "hub", color: "#6D28D9", website: "https://helixmind.online", authType: "apikey" },
  "heroku": { id: "heroku", alias: "her", name: "Heroku", icon: "hub", color: "#A21CAF", website: "https://us.inference.heroku.com", authType: "apikey" },
  "hyperagent": { id: "hyperagent", alias: "hy", name: "Hyperagent", icon: "hub", color: "#BE123C", website: "https://hyperagent.com", authType: "apikey" },
  "ideogram": { id: "ideogram", alias: "id", name: "Ideogram", icon: "hub", color: "#2563EB", website: "https://api.ideogram.ai", authType: "apikey" },
  "inner-ai": { id: "inner-ai", alias: "inn", name: "Inner Ai", icon: "hub", color: "#7C3AED", website: "https://chatapi.innerai.com", authType: "apikey" },
  "kenari": { id: "kenari", alias: "ke", name: "Kenari", icon: "hub", color: "#DB2777", website: "https://kenari.id", authType: "apikey" },
  "kie": { id: "kie", alias: "ki", name: "Kie", icon: "hub", color: "#DC2626", website: "https://api.kie.ai", authType: "apikey" },
  "kimi-coding": { id: "kimi-coding", alias: "kim", name: "Kimi Coding", icon: "hub", color: "#0D9488", website: "https://api.kimi.com", authType: "oauth" },
  "kimi-coding-apikey": { id: "kimi-coding-apikey", alias: "kimi", name: "Kimi Coding Apikey", icon: "hub", color: "#0891B2", website: "https://api.kimi.com", authType: "apikey" },
  "lambda-ai": { id: "lambda-ai", alias: "la", name: "Lambda Ai", icon: "hub", color: "#9333EA", website: "https://api.lambda.ai", authType: "apikey" },
  "leonardo": { id: "leonardo", alias: "le", name: "Leonardo", icon: "hub", color: "#C026D3", website: "https://cloud.leonardo.ai", authType: "apikey" },
  "llamagate": { id: "llamagate", alias: "lla", name: "Llamagate", icon: "hub", color: "#E11D48", website: "https://llamagate.ai", authType: "apikey" },
  "maritalk": { id: "maritalk", alias: "ma", name: "Maritalk", icon: "hub", color: "#F97316", website: "https://chat.maritaca.ai", authType: "apikey" },
  "meta-llama": { id: "meta-llama", alias: "met", name: "Meta Llama", icon: "hub", color: "#65A30D", website: "https://api.llama.com", authType: "apikey" },
  "mlx-gemma": { id: "mlx-gemma", alias: "ml", name: "Mlx Gemma", icon: "hub", color: "#6D28D9", website: "http://localhost:11435", authType: "apikey" },
  "mlx-qwen": { id: "mlx-qwen", alias: "mlx", name: "Mlx Qwen", icon: "hub", color: "#A21CAF", website: "http://localhost:11436", authType: "apikey" },
  "moonshot": { id: "moonshot", alias: "moo", name: "Moonshot", icon: "hub", color: "#BE123C", website: "https://api.moonshot.ai", authType: "apikey" },
  "muse-code": { id: "muse-code", alias: "mus", name: "Muse Code", icon: "hub", color: "#2563EB", authType: "apikey" },
  "nanogpt": { id: "nanogpt", alias: "nan", name: "Nanogpt", icon: "hub", color: "#7C3AED", website: "https://nano-gpt.com", authType: "apikey" },
  "notion-web": { id: "notion-web", alias: "not", name: "Notion Web", icon: "hub", color: "#DB2777", website: "https://app.notion.com", authType: "apikey" },
  "nube": { id: "nube", alias: "nu", name: "Nube", icon: "hub", color: "#DC2626", website: "https://ai.nube.sh", authType: "apikey" },
  "orcarouter": { id: "orcarouter", alias: "or", name: "Orcarouter", icon: "hub", color: "#0D9488", website: "https://api.orcarouter.ai", authType: "apikey" },
  "plamo": { id: "plamo", alias: "pl", name: "Plamo", icon: "hub", color: "#C026D3", website: "https://api.platform.preferredai.jp", authType: "apikey" },
  "poe": { id: "poe", alias: "poe", name: "Poe", icon: "hub", color: "#E11D48", website: "https://api.poe.com", authType: "apikey" },
  "promptql": { id: "promptql", alias: "pr", name: "Promptql", icon: "hub", color: "#65A30D", website: "https://data.prompt.ql.app", authType: "apikey" },
  "qianfan": { id: "qianfan", alias: "qi", name: "Qianfan", icon: "hub", color: "#0284C7", website: "https://qianfan.baidubce.com", authType: "apikey" },
  "qiniu": { id: "qiniu", alias: "qin", name: "Qiniu", icon: "hub", color: "#6D28D9", website: "https://api.qnaigc.com", authType: "apikey" },
  "qwen-cloud": { id: "qwen-cloud", alias: "qwe", name: "Qwen Cloud", icon: "hub", color: "#A21CAF", website: "https://dashscope-intl.aliyuncs.com", authType: "apikey" },
  "qwen-cloud-token-plan": { id: "qwen-cloud-token-plan", alias: "qwen", name: "Qwen Cloud Token Plan", icon: "hub", color: "#BE123C", website: "https://token-plan.ap-southeast-1.maas.aliyuncs.com", authType: "apikey" },
  "raycast": { id: "raycast", alias: "ra", name: "Raycast", icon: "hub", color: "#2563EB", website: "https://backend.raycast.com", authType: "oauth" },
  "regolo": { id: "regolo", alias: "reg", name: "Regolo", icon: "hub", color: "#7C3AED", website: "https://api.regolo.ai", authType: "apikey" },
  "snowflake": { id: "snowflake", alias: "sn", name: "Snowflake", icon: "hub", color: "#DB2777", website: "https://{account}.snowflakecomputing.com", authType: "apikey" },
  "sumopod": { id: "sumopod", alias: "su", name: "Sumopod", icon: "hub", color: "#DC2626", website: "https://ai.sumopod.com", authType: "apikey" },
  "suno": { id: "suno", alias: "sun", name: "Suno", icon: "hub", color: "#EA580C", website: "https://studio-api.suno.ai", authType: "cookie" },
  "synthetic": { id: "synthetic", alias: "sy", name: "Synthetic", icon: "hub", color: "#CA8A04", website: "https://api.synthetic.new", authType: "apikey" },
  "tabitoken": { id: "tabitoken", alias: "ta", name: "Tabitoken", icon: "hub", color: "#16A34A", website: "https://tabitoken.com", authType: "apikey" },
  "token-kiosk": { id: "token-kiosk", alias: "tok", name: "Token Kiosk", icon: "hub", color: "#0891B2", website: "https://agent-router.gaib.ai", authType: "apikey" },
  "trae": { id: "trae", alias: "tr", name: "Trae", icon: "hub", color: "#4F46E5", website: "https://core-normal.trae.ai", authType: "oauth" },
  "udio": { id: "udio", alias: "ud", name: "Udio", icon: "hub", color: "#9333EA", website: "https://www.udio.com", authType: "apikey" },
  "upstage": { id: "upstage", alias: "up", name: "Upstage", icon: "hub", color: "#C026D3", website: "https://api.upstage.ai", authType: "apikey" },
  "v0-vercel": { id: "v0-vercel", alias: "v0", name: "V0 Vercel", icon: "hub", color: "#E11D48", website: "https://api.v0.dev", authType: "apikey" },
  "venice": { id: "venice", alias: "ven", name: "Venice", icon: "hub", color: "#F97316", website: "https://api.venice.ai", authType: "apikey" },
  "vercel-ai-gateway": { id: "vercel-ai-gateway", alias: "ver", name: "Vercel Ai Gateway", icon: "hub", color: "#65A30D", website: "https://ai-gateway.vercel.sh", authType: "apikey" },
  "volcengine": { id: "volcengine", alias: "vol", name: "Volcengine", icon: "hub", color: "#0284C7", website: "https://ark.cn-beijing.volces.com", authType: "apikey" },
  "volcengine-agent-plan": { id: "volcengine-agent-plan", alias: "volc", name: "Volcengine Agent Plan", icon: "hub", color: "#6D28D9", website: "https://ark.cn-beijing.volces.com", authType: "apikey" },
  "volcengine-coding-plan": { id: "volcengine-coding-plan", alias: "volce", name: "Volcengine Coding Plan", icon: "hub", color: "#A21CAF", website: "https://ark.cn-beijing.volces.com", authType: "apikey" },
  "wafer": { id: "wafer", alias: "wa", name: "Wafer", icon: "hub", color: "#BE123C", website: "https://pass.wafer.ai", authType: "apikey" },
  "wandb": { id: "wandb", alias: "wan", name: "Wandb", icon: "hub", color: "#2563EB", website: "https://api.inference.wandb.ai", authType: "apikey" },
  "writer": { id: "writer", alias: "wr", name: "Writer", icon: "hub", color: "#7C3AED", website: "https://api.writer.com", authType: "apikey" },
  "x5lab": { id: "x5lab", alias: "x5", name: "X5lab", icon: "hub", color: "#DB2777", website: "https://api.x5lab.dev", authType: "apikey" },
  "xai": { id: "xai", alias: "xa", name: "Xai", icon: "hub", color: "#DC2626", website: "https://api.x.ai", authType: "apikey" },
  "xai-oauth": { id: "xai-oauth", alias: "xai", name: "Xai Oauth", icon: "hub", color: "#EA580C", website: "https://api.x.ai", authType: "oauth" },
  "xiaomi-mimo-token-plan": { id: "xiaomi-mimo-token-plan", alias: "xi", name: "Xiaomi Mimo Token Plan", icon: "hub", color: "#16A34A", website: "https://token-plan-sgp.xiaomimimo.com", authType: "apikey" },
  "yi": { id: "yi", alias: "yi", name: "Yi", icon: "hub", color: "#0D9488", website: "https://api.lingyiwanwu.com", authType: "apikey" },
  "zai": { id: "zai", alias: "zai", name: "Zai", icon: "hub", color: "#0891B2", website: "https://api.z.ai", authType: "apikey" },
  "zed-hosted": { id: "zed-hosted", alias: "zed", name: "Zed Hosted", icon: "hub", color: "#4F46E5", website: "https://cloud.zed.dev", authType: "oauth" },
};

/** Derived, not hand-maintained: the curated FREE_TIER_PROVIDER_IDS list had drifted. */
export const GENERATED_FREE_TIER_PROVIDER_IDS: string[] = Object.keys(
  GENERATED_FREE_TIER_PROVIDERS
);
